# Generated by Django 2.2.12 on 2021-06-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoloc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='mpoly',
        ),
        migrations.AlterField(
            model_name='country',
            name='cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoloc.Continent'),
        ),
    ]
