# Generated by Django 2.2.12 on 2021-06-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoloc', '0002_auto_20210610_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.RemoveField(
            model_name='city',
            name='den',
        ),
    ]
