# Generated by Django 2.2.12 on 2021-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoloc', '0006_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='coord',
        ),
        migrations.RemoveField(
            model_name='point',
            name='country',
        ),
        migrations.AddField(
            model_name='point',
            name='srid',
            field=models.CharField(default=4326, max_length=10),
        ),
    ]
